# -*- coding: utf-8 -*-
{
    'name': "patient_engagement",
    'summary': """ """,
    'description': """ """,
    'author': "My Company",
    'website': "http://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '0.1',
    'external_dependencies': {
        'python': ['twilio'],
    },
    'depends': ['base', 'calendar', 'base_automation', 'mass_mailing',
                'opt_custom', 'inputmask_widget', 'opt_appointment','patient_form_line','acs_consent_form',
                'ivis_order_grouping',],
    'qweb': [
        'static/src/xml/templates.xml',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/scheduler.xml',
        'data/automated_actions.xml',
        'views/main_menu.xml',
        'data/templates.xml',

        'views/logs.xml',
        'views/recall.xml',
        'views/assets.xml',
        'views/no_show.xml',
        'views/thank_you.xml',
        'views/pe_setting.xml',
        'views/overdue_recall.xml',
        # 'views/online_requests.xml',
        'wizard/contact_patient.xml',
        'views/online_adjustment.xml',
        'views/messaging_history.xml',
        'views/order_ready.xml',
        'views/online_requests_tree.xml',
        'views/contact_lens_reorder.xml',
        'views/appointment_remainder.xml',
        'views/res_config_settings_view.xml',
        'views/contact_lens_order_ready.xml',
    ],
}
