# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    "name": "Order Grouping in SO",
    "version": "13.0.0.0.1",
    "author": "IVIS",
    "license": "AGPL-3",
    "depends": ["base", "sale", "sale_stock", "sale_management", "account", "opt_custom", "opt_insurance",
                "opt_diagnosis", "barcode", 'sale_stock_delivery_address','web', # 'ks_theme_kernel', 
                'opt_appointment', 'gws_google_maps'],
    "data": [
        "security/ir.model.access.csv",
        "report/sale_report.xml",
        "report/sale_order_portal.xml",
        "report/claim_manager.xml",
        "report/report_cms_watermark.xml",
        "views/opt_pos_menuitems.xml",
        "views/assets.xml",
        'views/dispensing_note.xml',
        'views/order_status.xml',
        "views/authorization_form.xml",
        "views/account_move_inherit.xml",
        "views/multi_order_type_views.xml",
        "views/multi_order_type_historical.xml",
        "views/product_template.xml",
        "views/product_product.xml",
        "views/sale_stock.xml",
        "views/claim_form.xml",
        "views/claim_page.xml",
        "views/spec_lens_treatment.xml",
        "views/res_partner.xml",
        # "views/account_payment.xml",
        # "wizard/multi_invoice_payment.xml",
        "views/spec_insurance.xml",
        "views/sale_order.xml",
        "views/sale_order_line.xml",
        "views/sale_order_line_hcpcs.xml",
        "views/calendar_event.xml",
        "views/discount_reason.xml",

        "views/menu_items.xml",
    ],
    "installable": True,
}
